import MainPageContainer from "@/containers/MainPageContainer";
import { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return <MainPageContainer />;
}
