import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@styles/globals.css";
import StoreProvider from "@/hoc/app/StoreProvider";
import AppProvider from "@/hoc/app/AppProvider";
import { useEffect } from "react";
import { ToastContainer } from "react-toastify";
import Header from "@/component/layout/Header";
import AppLayout from "@/layouts/AppLayout";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <AppProvider>
            {/* <AppLayout >{children}</AppLayout> */}
            <AppLayout >{children}</AppLayout>
          </AppProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
