import GuestLayout from '@/components/layout/GuestLayout';
import StoreProvider from '@/hoc/app/StoreProvider';
import '@styles/globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <GuestLayout>{children}</GuestLayout>
      </body>
    </html>
  );
}
